### PR TITLE
update readme

### PR DESCRIPTION
**Pull request by tjex**
Update links in readme and give credit.

Would be good to merge this one before refreshing the module online at golang.org

### CODE REVIEW

**Comment by julio-lopez** [comment]
LGTM.

Somewhat related but broader comment. In general it makes sense to submit changes to the original upstream project (zk-org/pretty in this case) and eventually use the upstream as a dependency instead of a fork. Now, in this case it seems that the upstream project has not been maintained for a while.

I wonder if it makes sense to at least take the few changes that were merged upstream (after reviewing them, I have not).

And maybe submitting a PR for the enhancements that Michael Menu added.

Just thinking out loud. Thoughts?

**Review by julio-lopez — APPROVED** [review]

**Comment by tjex** [comment]
It was @mcDevnagh initiative to move to our own managed fork. Mickael also suggested in #3 that we would be fine to just use upstream. I'm not sure what the decision making process was, but it revolved around wanting to manage our own dependancies - although I'm not sure why this one was chosen and no others. 

I actually thought that #3 was in fact syncing our fork with the upstream, but it seems not. Also upstream is on v0.3.1, while this fork started with v0.2.3 only. 

If it ever does become a hassle to maintain this way, we can always update the zk go.mod to use the kr/pretty again I guess?

**Comment by tjex** [comment]
maybe it's also annoying / senseless then to update this readme. 
It just always bugs me when I land on a project / readme and the documentation is an exact clone of the fork and doesn't give any contextual information...

**Comment by jurica** [comment]
If we stay with our fork I'd keep the readme, I agree with having a bit of context is nice.
So for now I'd vote for merging this PR.

**Review by jurica — APPROVED** [review]

**Comment by mcDevnagh** [comment]
I'll look into the implications of switching to the upstream, and post results [in a zk issue](https://github.com/zk-org/zk/issues/380). If it's minor, I'll create a PR.

**Pull request merged**
